export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';

export const ADD_ANIMELIST = 'ADD_ANIMELIST';
export const ANIMELIST_LOADING = 'ANIMELIST_LOADING';
export const ANIMELIST_FAILED = 'ANIMELIST_FAILED';